[package]
name = "keyboard-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
chrono = "0.4.26"
env_logger = "0.10.0"
evdev = { version = "0.12.1", features = ["tokio"] }
log = "0.4.19"
tokio = { version = "1.29.1", features = ["full"] }
